column_width              = 100
line_endings              = "Unix"
indent_type               = "Spaces"
indent_width              = 2
quote_style               = "ForceDouble"
no_call_parentheses       = false
syntax                    = "LuaJIT"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
