#!/bin/sh

# install neovim
sudo apt install neovim

# install Vim-Plug
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# copy/paste enable
sudo apt install xclip

# install python support
pip install pynvim

# install node support
npm i -g neovim

# install ranger
sudo apt install ranger
pip install ueberzug
mkdir -p ~/.config/ranger/plugins/ranger_devicons
git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons

echo 
echo 
echo 
echo 
echo 
echo "Successfully installed!"
echo "In VSCode, point your init.vim path to \"\$HOME/.config/nvim/\""

