#!/bin/sh

cp ~/.config/Code/User/keybindings.json ./vscode/Code-configs
cp ~/.config/Code/User/settings.json ./vscode/Code-configs/

echo
echo "VSCode settings and keybindings were sucessfully saved."
echo
