require('v.utils').set_viml_options('tokyonight', {
  style = 'storm',
  italic_coments = true,
  italic_keywords = true,
  italic_variables = false,
  italic_functions = false,
  transparent = false,
  transparent_sidebar = false,
  hide_inactive_statusline = true,
  dark_sidebar = true,
  dark_float = true,
  sidebars = {
    'qf',
    'NvimTree',
    'NvimTree_*',
    'terminal',
    'packer',
    'spectre_panel',
  },
})
